/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kalkulatormini;
import javax.swing.JOptionPane;


/**
 *
 * @author user
 */
public class Kalkulator extends javax.swing.JFrame {

    /**
     * Creates new form Kalkulator
     */
    public Kalkulator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Tambah = new javax.swing.JButton();
        Kali = new javax.swing.JButton();
        Kurang = new javax.swing.JButton();
        Bagi = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ValueNilaiPertama = new javax.swing.JTextField();
        ValueHasil = new javax.swing.JTextField();
        ValueNilaiKedua = new javax.swing.JTextField();
        Akar = new javax.swing.JButton();
        Pangkat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Tambah.setText("Tambah");
        Tambah.setActionCommand("Pertambahan");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        Kali.setText("Kali");
        Kali.setActionCommand("Perkalian");
        Kali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KaliActionPerformed(evt);
            }
        });

        Kurang.setText("Kurang");
        Kurang.setActionCommand("Pengurangan");
        Kurang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KurangActionPerformed(evt);
            }
        });

        Bagi.setText("Bagi");
        Bagi.setActionCommand("Pembagian");
        Bagi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BagiActionPerformed(evt);
            }
        });

        jLabel1.setText("Nilai Pertama");

        jLabel2.setText("Nilai Kedua");

        jLabel3.setText("Hasil");

        ValueNilaiPertama.setActionCommand("<Not Set>");

        ValueHasil.setEditable(false);

        ValueNilaiKedua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueNilaiKeduaActionPerformed(evt);
            }
        });

        Akar.setText("Akar");
        Akar.setActionCommand("Pembagian");
        Akar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AkarActionPerformed(evt);
            }
        });

        Pangkat.setText("Pangkat");
        Pangkat.setActionCommand("Pembagian");
        Pangkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PangkatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ValueNilaiPertama, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValueHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ValueNilaiKedua, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Pangkat)
                    .addComponent(Akar)
                    .addComponent(Kali)
                    .addComponent(Tambah)
                    .addComponent(Kurang)
                    .addComponent(Bagi))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Tambah)
                        .addComponent(ValueNilaiPertama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Kurang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Kali)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Bagi))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ValueNilaiKedua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Akar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Pangkat)
                        .addComponent(ValueHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3))
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KurangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KurangActionPerformed
        String nilaiPertama = ValueNilaiPertama.getText().trim();
        String nilaiKedua = ValueNilaiKedua.getText().trim();
//        System.out.println("Nilai pertama (String): " + nilaiPertama);
//        System.out.println("Nilai kedua (String): " + nilaiKedua);
        try {
            double nilaiAngkaPertama = Double.parseDouble(nilaiPertama);
            double nilaiAngkaKedua = Double.parseDouble(nilaiKedua);
        
            double hasil = nilaiAngkaPertama - nilaiAngkaKedua;
            ValueHasil.setText(Double.toString(hasil));
//            ValueNilaiPertama.setText("");
//            ValueNilaiKedua.setText("");
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Inputan masih kosong");
            ValueNilaiPertama.setText("");
            ValueNilaiKedua.setText("");
            ValueHasil.setText("");
        }
    }//GEN-LAST:event_KurangActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        String nilaiPertama = ValueNilaiPertama.getText().trim();
        String nilaiKedua = ValueNilaiKedua.getText().trim();
//        System.out.println("Nilai pertama (String): " + nilaiPertama);
//        System.out.println("Nilai kedua (String): " + nilaiKedua);
        try {
            double nilaiAngkaPertama = Double.parseDouble(nilaiPertama);
            double nilaiAngkaKedua = Double.parseDouble(nilaiKedua);
        
            double hasil = nilaiAngkaPertama + nilaiAngkaKedua;
            ValueHasil.setText(Double.toString(hasil));
//            ValueNilaiPertama.setText("");
//            ValueNilaiKedua.setText("");
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Inputan masih kosong");
            ValueNilaiPertama.setText("");
            ValueNilaiKedua.setText("");
            ValueHasil.setText("");
        }
        
        
        
    }//GEN-LAST:event_TambahActionPerformed

    private void ValueNilaiKeduaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueNilaiKeduaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValueNilaiKeduaActionPerformed

    private void KaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KaliActionPerformed
        String nilaiPertama = ValueNilaiPertama.getText().trim();
        String nilaiKedua = ValueNilaiKedua.getText().trim();
//        System.out.println("Nilai pertama (String): " + nilaiPertama);
//        System.out.println("Nilai kedua (String): " + nilaiKedua);
        try {
            double nilaiAngkaPertama = Double.parseDouble(nilaiPertama);
            double nilaiAngkaKedua = Double.parseDouble(nilaiKedua);
        
            double hasil = nilaiAngkaPertama * nilaiAngkaKedua;
            ValueHasil.setText(Double.toString(hasil));
//            ValueNilaiPertama.setText("");
//            ValueNilaiKedua.setText("");
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Inputan masih kosong");
            ValueNilaiPertama.setText("");
            ValueNilaiKedua.setText("");
            ValueHasil.setText("");
        }
    }//GEN-LAST:event_KaliActionPerformed

    private void BagiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BagiActionPerformed
        String nilaiPertama = ValueNilaiPertama.getText().trim();
        String nilaiKedua = ValueNilaiKedua.getText().trim();
//        System.out.println("Nilai pertama (String): " + nilaiPertama);
//        System.out.println("Nilai kedua (String): " + nilaiKedua);
        try {
            double nilaiAngkaPertama = Double.parseDouble(nilaiPertama);
            double nilaiAngkaKedua = Double.parseDouble(nilaiKedua);
        
            double hasil = nilaiAngkaPertama / nilaiAngkaKedua;
            ValueHasil.setText(Double.toString(hasil));
//            ValueNilaiPertama.setText("");
//            ValueNilaiKedua.setText("");
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Inputan masih kosong");
            ValueNilaiPertama.setText("");
            ValueNilaiKedua.setText("");
            ValueHasil.setText("");
        }
    }//GEN-LAST:event_BagiActionPerformed

    private void AkarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AkarActionPerformed
        String nilaiPertama = ValueNilaiPertama.getText().trim();
        String nilaiKedua = ValueNilaiKedua.getText().trim();
//        System.out.println("Nilai pertama (String): " + nilaiPertama);
//        System.out.println("Nilai kedua (String): " + nilaiKedua);
        try {
            double nilaiAngkaPertama = Double.parseDouble(nilaiPertama);
            double nilaiAngkaKedua = Double.parseDouble(nilaiKedua);
        
            double hasil = Math.sqrt(nilaiAngkaPertama);
            double hasil2 = Math.sqrt(nilaiAngkaKedua);
            ValueHasil.setText(Double.toString(hasil)+ " dan " + Double.toString(hasil2));
//            ValueNilaiPertama.setText("");
//            ValueNilaiKedua.setText("");
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Inputan masih kosong");
            ValueNilaiPertama.setText("");
            ValueNilaiKedua.setText("");
            ValueHasil.setText("");
        }
    }//GEN-LAST:event_AkarActionPerformed

    private void PangkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PangkatActionPerformed
        String nilaiPertama = ValueNilaiPertama.getText().trim();
        String nilaiKedua = ValueNilaiKedua.getText().trim();
//        System.out.println("Nilai pertama (String): " + nilaiPertama);
//        System.out.println("Nilai kedua (String): " + nilaiKedua);
        try {
            double nilaiAngkaPertama = Double.parseDouble(nilaiPertama);
            double nilaiAngkaKedua = Double.parseDouble(nilaiKedua);
        
            double hasil = Math.pow(nilaiAngkaPertama, nilaiAngkaKedua);
            ValueHasil.setText(Double.toString(hasil));
//            ValueNilaiPertama.setText("");
//            ValueNilaiKedua.setText("");
        }catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Inputan masih kosong");
            ValueNilaiPertama.setText("");
            ValueNilaiKedua.setText("");
            ValueHasil.setText("");
        }
    }//GEN-LAST:event_PangkatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kalkulator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kalkulator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Akar;
    private javax.swing.JButton Bagi;
    private javax.swing.JButton Kali;
    private javax.swing.JButton Kurang;
    private javax.swing.JButton Pangkat;
    private javax.swing.JButton Tambah;
    private javax.swing.JTextField ValueHasil;
    private javax.swing.JTextField ValueNilaiKedua;
    private javax.swing.JTextField ValueNilaiPertama;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
